user:
  outputs:
    default:
      account: ndxlicu-pa46704
      auth_type: password
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 30
      database: LINEAGE
      password: RajAstra123!@#
      retry_on_database_errors: true
      role: null
      schema: testing
      threads: 6
      type: snowflake
      user: rajeshmachanastra
      warehouse: COMPUTE_WH
  target: default
