version: 2

sources:
  # 🔷 PUBLIC schema tables
  - name: raw_public
    database: LINEAGE
    schema: PUBLIC

    tables:
      - name: raw_customers
      - name: raw_orders

  # 🔷 TESTING schema tables
  - name: raw_testing
    database: LINEAGE
    schema: TESTING

    tables:
      - name: raw_users
      - name: raw_transactions
      - name: raw_payments_log